// Run: npm run test:news
// Invariants of src/data/news/posts.json (generated by tools/import-wp-news.mjs) that the templates rely on.
import assert from 'node:assert/strict';
import fs from 'node:fs';

const posts = JSON.parse(fs.readFileSync('src/data/news/posts.json', 'utf8'));
const categories = JSON.parse(fs.readFileSync('src/data/content/media-hub/page.en.json', 'utf8')).explore.categories.map((c) => c.key);
const KNOWN = new Set([...categories, 'interviews']);

assert.ok(posts.length > 0, 'posts.json is empty');
const seen = new Set();
const en = new Set(posts.filter((p) => p.language === 'en').map((p) => p.slug));
for (const p of posts) {
  const k = `${p.slug}|${p.language}`;
  assert.ok(!seen.has(k), `duplicate record ${k}`);
  seen.add(k);
  assert.match(p.slug, /^[\p{L}\p{N}-]+$/u, `bad slug "${p.slug}"`);
  assert.ok(['en', 'ar'].includes(p.language), `bad language on ${k}`);
  assert.match(p.date, /^\d{4}-\d{2}-\d{2}$/, `bad date on ${k}`);
  assert.ok(KNOWN.has(p.category), `unknown category "${p.category}" on ${k}`);
  assert.ok(p.title.trim(), `empty title on ${k}`);
  assert.ok(p.body.trim() || p.excerpt.trim(), `no body and no excerpt on ${k}`);
  assert.ok(!/<(script|iframe)\b/i.test(p.body), `raw script/iframe in ${k}`);
  assert.ok(!/<!--/.test(p.body), `block comment left in ${k}`);
  for (const m of p.body.matchAll(/data-youtube="([^"]*)"/g)) assert.match(m[1], /^[A-Za-z0-9_-]{11}$/, `bad video id in ${k}`);
  if (p.old_url) assert.ok(p.old_url.startsWith('/'), `old_url not a path on ${k}`);
  if (p.language === 'ar') assert.ok(en.has(p.slug), `Arabic record without an English one: ${p.slug}`);
}

// Home cards point at real posts
const home = JSON.parse(fs.readFileSync('src/data/content/home/news.en.json', 'utf8'));
for (const slug of home.posts) assert.ok(en.has(slug), `home/news post "${slug}" is not in posts.json`);
const homeNews = JSON.parse(fs.readFileSync('src/data/news.json', 'utf8'));
for (const p of homeNews.posts) assert.ok(en.has(p.slug), `news.json slug "${p.slug}" is not in posts.json`);

// Images: the keys must resolve to a file; missing files only warn (download step)
const missing = [...new Set(posts.map((p) => p.image).filter(Boolean))].filter((key) => !fs.readdirSync('src/assets/news').some((f) => f.replace(/\.[a-z0-9]+$/i, '') === key.replace('news/', '')));
if (missing.length) console.warn(`news: ${missing.length} featured image file(s) not downloaded yet (node tools/download-news-images.mjs --browser)`);

console.log(`news: ok (${posts.length} records, ${en.size} slugs)`);
